In [96]:
# 3 terms:
# the first term corresponds to taking no null transitions
# the second corresponds to taking 1 null transition
# The third corresponds to taking 2 null transitions (np.dot(Q, Q))  applying the null transition matrix twice.

import numpy as np

A = np.array([[1/2, 1/6, 1/6], [0, 0, 1/3], [3/4, 1/4, 0]])

B = np.array([[[1, 1/2, 1], [0, 0, 1/3], [0, 0, 0]], [[0, 1/2, 0], [1, 1, 2/3], [1, 1, 1]]])

Q = np.array([[0, 0, 1/6], [1/3, 0, 1/3], [0, 0, 0]])

alpha_0 = np.array([[1, 0, 0]])
print("ALPHA 0 \n",alpha_0) 

alpha_1_prime = np.dot((A * B[0]).T, alpha_0.T)
# print("ALPHA 1 PRIME",alpha_1_prime)

# print("alpha 0 shape",alpha_0.shape)
# print("A shape",A.shape)
# print("B 0 shape",B[0].shape)
# print("alpha prime shape", alpha_1_prime.shape)

alpha_1 = alpha_1_prime + np.dot(Q.T, alpha_1_prime) + np.dot(np.dot(Q, Q).T, alpha_1_prime)
print("ALPHA 1 \n",alpha_1)     

alpha_2_prime = np.dot((A * B[1]).T, alpha_1)
# print("ALPHA 2 PRIME",alpha_2_prime)
alpha_2 = alpha_2_prime + np.dot(Q.T, alpha_2_prime) + np.dot(np.dot(Q, Q).T, alpha_2_prime)
print("ALPHA 2 \n",alpha_2)

alpha_3_prime = np.dot((A * B[1]).T, alpha_2)
# print("ALPHA 3 PRIME",alpha_3_prime)
alpha_3 = alpha_3_prime + np.dot(Q.T, alpha_3_prime) + np.dot(np.dot(Q, Q).T, alpha_3_prime)
print("ALPHA 3 \n",alpha_3)

alpha_4_prime = np.dot((A * B[0]).T, alpha_3)
print("ALPHA 4 \n",alpha_4_prime)

ALPHA 0 
 [[1 0 0]]
ALPHA 1 
 [[0.52777778]
 [0.08333333]
 [0.28240741]]
ALPHA 2 
 [[0.25      ]
 [0.11458333]
 [0.09837963]]
ALPHA 3 
 [[0.08892747]
 [0.04542824]
 [0.05542695]]
ALPHA 4 
 [[0.04446373]
 [0.00741062]
 [0.01986883]]


In [113]:
marginal = alpha_4_prime.sum(axis=0)
print(marginal)

[0.07174318]


In [112]:

element_1 = alpha_3[0, 0]  
element_2 = alpha_3[1, 0]  
element_3 = alpha_3[2, 0]
print("Element 1:", element_1)
print("Element 2:", element_2)
print("Element 3:", element_3)

state_3_1 = alpha_3[0, 0] * beta_3[0, 0]
state_3_2 = alpha_3[1, 0] * beta_3[1, 0]
state_3_3 = alpha_3[2, 0] * beta_3[2, 0]

print("state 3 --- ",state_3_1+state_3_2+state_3_3)

state_4 = alpha_4 * beta_4.T
print("state 4", state_4)
print("sum of state 4", state_4.sum(axis=0))

Element 1: 0.08892746913580248
Element 2: 0.04542824074074074
Element 3: 0.05542695473251028
state 3 ---  0.0009358156820529508
state 4 [[0.04693394]
 [0.00741062]
 [0.03016136]]
sum of state 4 [0.08450592]


In [ ]:
beta_4 = np.array([[1, 1, 1]])
print("BETA 4",beta_4) 

beta_3_prime = np.dot((A * B[0]).T, beta_4.T)
beta_3 = beta_3_prime + np.dot(Q.T, beta_3_prime) + np.dot(np.dot(Q, Q).T, beta_3_prime)
print("BETA 3",beta_3)    

beta_2_prime = np.dot((A * B[1]).T, beta_3)
beta_2 = beta_2_prime + np.dot(Q.T, beta_2_prime) + np.dot(np.dot(Q, Q).T, beta_2_prime)
print("BETA 2",beta_2) 

beta_1_prime = np.dot((A * B[1]).T, beta_2)
beta_1 = beta_2_prime + np.dot(Q.T, beta_1_prime) + np.dot(np.dot(Q, Q).T, beta_1_prime)
print("BETA 1",beta_1) 

beta_0_prime = np.dot((A * B[0]).T, beta_1)
beta_0 = beta_0_prime + np.dot(Q.T, beta_0_prime) + np.dot(np.dot(Q, Q).T, beta_0_prime)
print("BETA 0",beta_0) 
